[package]
name = "seoul"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "30"
winit = "0.30"
cpal = "0.18"
realfft = "3"
ringbuf = "0.5"
triple_buffer = "9"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
notify = "8"
arrayvec = "0.7"
rand = "0.10"
png = "0.18.1"
glyphon = "0.12"

[profile.release]
lto = "thin"
codegen-units = 1
